# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  # The following line is different from the template:
  # we need to install tic from our local source!
  - R -q -e 'remotes::install_local(getwd(), force = TRUE); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#stages: smoke, full
stages:
- name: test
- name: full
  if: branch = master

#jobs: 5x Linux (1x with deployment), 1x OS X
jobs:
  include:
  - stage: test
    r: devel
  - r: 3.2
  - stage: full
    r: release
    env:
    - BUILD_PKGDOWN=true
  - os: osx
    r: release
  - r: 3.4
  - r: 3.3
  - r: 3.1
  allow_failures:
  - r: 3.1

#matrix: Early abortion of failed builds
matrix:
  fast_finish: true

#services
services:
