# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: false
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#addons
addons:
  apt:
    packages:
    - libmagick++-dev
    - libssh2-1-dev

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
    env:
    - BUILD_PKGDOWN=true
  - r: oldrel
  - r: devel
  - os: osx
    osx_image: xcode7.3
    r: release
    latex: false

#notifications
notifications:
  email:
    on_success: change
    on_failure: change

#before_script
before_script:
- echo -e "\e[31mtest\e[39m"
- R -q -e 'devtools::install_cran("roxygen2"); devtools::load_all(); prepare_all_stages()'

#after_success
after_success:
- echo -e "\e[31mtest\e[39m"
- R -q -e 'devtools::load_all(); after_success()'

#deploy // https://github.com/travis-ci/travis-build/blob/85ef7108/lib/travis/build/addons/deploy/script.rb#L100-L107
deploy:
  provider: script
  script: echo -e "\e[31mtest\e[39m"
  on:
    all_branches: true

# Custom parts:

#r_github_packages
r_github_packages:

#r_packages
r_packages:

#services
services:

#before_install
before_install:
